---
- name: shutdown
  hosts: all
  become: yes
  tasks:
    - name: shutdown_FreeBSD
      ansible.builtin.command:
        cmd: 'shutdown -p now'
      when: ansible_os_family == "FreeBSD"
    - name: shutdown_OpenBSD
      ansible.builtin.command:
        cmd: 'shutdown -hp now'
      when: ansible_os_family == "OpenBSD"
    - name: shutdown_Linux
      ansible.builtin.command:
        cmd: 'systemctl poweroff'
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
