---
# tasks file for apache
- name: install httpd
  ansible.builtin.yum:
    name: httpd
    state: present
- name: enabled httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
- name: enabled firewall
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
- name: config firewall
  ansible.builtin.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
- name: index
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
