---
- name: install packages
  hosts: dev, test, prod
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.yum:
        name:
          - php
          - mariadb
        state: present
- name: install packages
  hosts: dev
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.yum:
        name:
          - "@Development Tools"
        state: present
    - name: update
      ansible.builtin.yum:
        name: "*"
        state: latest
